name: SkyBlocks
authors: [GiantQuartz, DaDevGuy]
main: Skyblocks\DaDevGuy\SkyBlock
version: 1.0.0
api: [4.0.0]

permissions:
  skyblock.interaction:
    description: Allows players to interact with an island regardless of whether they belong to it
    default: op
